<div class="container">
	<h2>Coordonnées de facturation : </h2>
	<form action="orders/saveBillingDetails" method="post" id="account">
		<div id="billing-data">
			<div class="radio">
				<input type="radio" name="civility" value="M." id="M" required <?= ((isset($enteredData['civility']) AND $enteredData['civility'] == 'M.') ? 'checked' : (isset($customer['civility']) AND $customer['civility'] == 'M.')? 'checked' : null) ?>/><label for="M">M.</label>
				<input type="radio" name="civility" value="Mme" id="Mme" required <?= ((isset($enteredData['civility']) AND $enteredData['civility'] == 'Mme') ? 'checked' : (isset($customer['civility']) AND $customer['civility'] == 'Mme')? 'checked' : null) ?>/> <label for="Mme">Mme</label>
				<input type="radio" name="civility" value="Mlle" id="Mlle" required <?= ((isset($enteredData['civility']) AND $enteredData['civility'] == 'Mlle') ? 'checked' : (isset($customer['civility']) AND $customer['civility'] == 'Mlle')? 'checked' : null) ?>/> <label for="Mlle">Mlle</label>
			</div>
			<input type="text" placeholder="Prénom" name="firstName" value="<?= (isset($enteredData['firstName']))? htmlspecialchars($enteredData['firstName']) : htmlspecialchars($customer['firstName'])?>" required>
			<input type="text" placeholder="Nom" name="lastName" value="<?= (isset($enteredData['lastName']))? htmlspecialchars($enteredData['lastName']) : htmlspecialchars($customer['lastName'])?>" required>
			<textarea name="address" cols="30" rows="10" placeholder="Adresse" required><?= (isset($enteredData['addressName']))? htmlspecialchars($enteredData['address']) : htmlspecialchars($customer['address'])?></textarea>
			<input type="text" placeholder="Code postal" name="zipCode" value="<?= (isset($enteredData['zipCode']))? htmlspecialchars($enteredData['zipCode']) : htmlspecialchars($customer['zipCode'])?>" required>
			<input type="text" placeholder="Commune" name="city" value="<?= (isset($enteredData['city']))? htmlspecialchars($enteredData['city']) : htmlspecialchars($customer['city'])?>" required>
			<input type="text" placeholder="Pays" name="country" value="<?= (isset($enteredData['country']))? htmlspecialchars($enteredData['country']) : htmlspecialchars($customer['country'])?>" required>
			<input type="text" placeholder="Numéro de téléphone" name="phoneNumber" value="<?= (isset($enteredData['phoneNumber']))? htmlspecialchars($enteredData['phoneNumber']) : htmlspecialchars($customer['phoneNumber'])?>" required>
		</div>
		<button type="submit">Valider</button>
	</form>
</div>