<div class="container">
	<h1>Commande enregistrée</h1>
	<p>Votre commande vous sera livrée dans les meilleurs délais. 
		<br><small>(Enfin, elle le serait si ce site n'était pas juste une démo et vendait vraiment des produits. Si vous êtes triste, allez plutôt les acheter chez Aroma-Zone !)</small></p> 
	<p class="margin-bottom">Merci d'avoir commandé chez Aroma-Clone !</p>	
	<div id="liens">
		<a href="customers/account">Mon compte</a>
		<a href="products/showSome">Retourner&nbsp;à&nbsp;l'accueil</a>
	</div>
</div>