<div class="container" id="login">
	<h2>Modifier mon mot de passe : </h2>
	<form action="customers/passwordUpdate" method="post" id="account">
		<div id="password-update">
			<input type="password" placeholder = "Mot de passe actuel" name="password" value='<?= $enteredData['password'] ?>' required>
			<input type="password" placeholder = "Nouveau mot de passe" name="newPassword" required>
			<input type="password" placeholder = "Confirmation du nouveau mot de passe" name="newPassword2" required>
			<input type="hidden" name="CSRFToken" value="<?= $_SESSION['customer']['CSRFToken'] ?>">
		</div>
		<button type="submit">Mettre à jour</button>
	</form>
</div>