<div class="container">
	<h2>Découvrez tous nos produits : </h2>
	<?php if($pagination['productsNumber'] > 0): ?>
	<ul id="products">
		<?php foreach($pagination['products'] as $product): ?>
			<li>
				<a href="products/showOne?id=<?= htmlspecialchars($product['productId']) ?>">
				<h3><?= htmlspecialchars($product['productName']) ?></h3>
				<img src="public/resources/images/products/<?= htmlspecialchars($product['imagePath']) ?>" alt="<?= htmlspecialchars($product['productName']) ?>"></a>
				<p><?= htmlspecialchars($product['description']) ?></p>
				<span class="bold"><?php
				$price = htmlspecialchars($product['priceTTC']);
				$price = number_format($price, 2, ',','&nbsp;');
				echo $price.' €'; ?></span>		
				<div id="liens">
					<a href="products/showOne?id=<?= htmlspecialchars($product['productId']) ?>">Dites-m'en plus !</a>
					<a href="shoppingCart/addProduct?id=<?= htmlspecialchars($product['productId']) ?>">Ajouter&nbsp;au&nbsp;panier</a>
				</div>
			</li>
		<?php endforeach; ?>
	</ul>
	<nav id="pagination">
		<?php for ($i=1; $i <= $pagination['pagesNumber']; $i++) : ?>
			<?php if ($i == $pagination['currentPage']) : ?>
				<button class="button" disabled><?= $i ?></button>
			<?php else : ?>
				<a href="products/showSome?page=<?= $i ?>"><button class="button"><?= $i ?></button></a>
			<?php endif; ?>
		<?php endfor; ?>
		<p>
			<?php if ($pagination['paginationStartShowed'] == $pagination['paginationEnd']) : ?>
			Produit <?= $pagination['paginationStartShowed'] ?>
			<?php else : ?>
			Produits <?= $pagination['paginationStartShowed'] ?> à <?= $pagination['paginationEnd'] ?>
			<?php endif; ?>
			 sur <?= $pagination['productsNumber'] ?></p>
		<a href="products/showAll" id="all-products-link">Afficher tous les produits</a>
	</nav>

	<?php endif; ?>
</div>